blueprint:
  name: Termostato Netatmo con Logica Stagionale Reattiva
  description: Controllo intelligente del termostato Netatmo basato su temperatura interna, esterna, stagione e condizioni ambientali, reagisce subito ai cambiamenti.
  domain: automation
  input:
    climate_entity:
      name: Termostato Netatmo
      description: "Il termostato Netatmo da controllare con questo blueprint."
      selector:
        entity:
          domain: climate
    internal_temp_sensor:
      name: Sensore temperatura interna
      description: "Sensore della temperatura interna utilizzato per confrontare con le soglie stagionali."
      selector:
        entity:
          domain: sensor
    external_temp_sensor:
      name: Sensore temperatura esterna
      description: "Sensore della temperatura esterna usato per determinare se è inverno o estate."
      selector:
        entity:
          domain: sensor
    winter_min_temp:
      name: Soglia minima interna in inverno
      description: "Temperatura minima interna accettabile durante l'inverno. Se la temperatura scende sotto questo valore il termostato entra in modalità riscaldamento."
      selector:
        number:
          min: 5
          max: 25
          step: 0.5
    winter_max_temp:
      name: Soglia massima interna in inverno
      description: "Temperatura massima interna in inverno. Se la temperatura supera questo valore, il riscaldamento può essere spento o il termostato messo in away."
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
    summer_min_temp:
      name: Soglia minima interna in estate
      description: "Temperatura minima interna accettabile durante l'estate. Se la temperatura scende sotto questo valore il termostato può essere acceso."
      selector:
        number:
          min: 5
          max: 25
          step: 0.5
    summer_max_temp:
      name: Soglia massima interna in estate
      description: "Temperatura massima interna in estate. Se la temperatura supera questo valore il termostato può essere spento o messo in away."
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
    seasonal_threshold:
      name: Soglia temperatura esterna per distinguere estate/inverno
      description: "Se la temperatura esterna è inferiore a questa soglia, il blueprint considera l'ambiente in inverno; altrimenti estate."
      selector:
        number:
          min: 5
          max: 25
          step: 0.5
    target_temp:
      name: Temperatura target interna
      description: "Temperatura interna desiderata quando il termostato entra in modalità manuale o preset scelto."
      selector:
        number:
          min: 10
          max: 30
          step: 0.5
    preset_mode:
      name: Modalità Netatmo da usare
      description: "Preset da impostare sul termostato quando la logica decide di riscaldare o raffreddare la stanza."
      selector:
        select:
          options:
            - manual
            - away
            - frost guard
    presence_entity:
      name: Sensore di presenza (opzionale)
      description: "Se configurato, il termostato agisce solo quando la presenza è rilevata. Se vuoto, ignora la presenza."
      default: ""
      selector:
        entity:
          domain: binary_sensor
    window_entity:
      name: Sensore finestra aperta (opzionale)
      description: "Se configurato, quando la finestra è aperta il termostato va in 'away' e ripristina lo stato precedente alla chiusura."
      default: ""
      selector:
        entity:
          domain: binary_sensor

trigger:
  - platform: state
    entity_id: "{{ input.internal_temp_sensor }}"
  - platform: state
    entity_id: "{{ input.external_temp_sensor }}"
  - platform: state
    entity_id: "{{ input.presence_entity }}"
    for:
      seconds: 0
  - platform: state
    entity_id: "{{ input.window_entity }}"
    for:
      seconds: 0

action:
  - variables:
      internal_temp: "{{ states(input.internal_temp_sensor) | float }}"
      external_temp: "{{ states(input.external_temp_sensor) | float }}"
      is_home: "{{ input.presence_entity == '' or is_state(input.presence_entity, 'on') }}"
      is_window_closed: "{{ input.window_entity == '' or is_state(input.window_entity, 'off') }}"
      is_winter: "{{ external_temp < input.seasonal_threshold }}"
      min_temp: "{{ input.winter_min_temp if is_winter else input.summer_min_temp }}"
      max_temp: "{{ input.winter_max_temp if is_winter else input.summer_max_temp }}"
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ internal_temp < min_temp and is_home and is_window_closed }}
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: "{{ input.climate_entity }}"
            data:
              preset_mode: "{{ input.preset_mode }}"
          - service: climate.set_temperature
            target:
              entity_id: "{{ input.climate_entity }}"
            data:
              temperature: "{{ input.target_temp }}"
      - conditions:
          - condition: template
            value_template: >
              {{ internal_temp > max_temp or not is_home or not is_window_closed }}
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: "{{ input.climate_entity }}"
            data:
              preset_mode: away

